### ISSUE TITLE
method not found: 'constructInsertSql'

### ISSUE THREAD

**Issue by Ufo28** [ustims/DartORM-MySQL#1]
Testing user model with mysql adapter:
Unhandled exception:
Uncaught Error: Class 'MySQLDBAdapter' has no instance method 'constructInsertSql'.

NoSuchMethodError: method not found: 'constructInsertSql'
Receiver: Instance of 'MySQLDBAdapter'
Arguments: [Instance of 'Insert']
Stack Trace:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      MySQLDBAdapter.insert.<insert_async_body> (package:dart_orm_adapter_mysql/dart_orm_adapter_mysql.dart:163:52)
#3      _asyncCatchHelper.<anonymous closure> (dart:core-patch/core_patch.dart:11)
#4      _RootZone.runBinary (dart:async/zone.dart:1160)
#5      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:511)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:570)
#7      _Future._completeError (dart:async/future_impl.dart:366)
#8      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:421)
#9      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#10     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#11     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)

**Comment by ustims** [comment]
Thanks, I will check it soon.

**Comment by rayokota** [comment]
I think this is a problem with the package at pub.dartlang.org.  The package of dart_orm that is labeled as 0.0.12 is actually 0.0.11.

**Comment by vgordievskiy** [comment]
Hi all.
class MySQLDBAdapter using  "this.constructSelectSql(select);" in method select (line num 109), but SQLAdapter are providing this as static member.

**Comment by vgordievskiy** [comment]
and line 163 in method insert - this.constructInsertSql(insert);

**Comment by ustims** [comment]
Hi guys. Sorry for late response.

As @rayokota said, there were some problems with DartORM pub package and its version. I have increased a version to 0.0.13 and it seems that code has been updated. So please try it.

Methods like constructInsertSql should not be static anymore.
